export const routes = {
  CREATE: (profileId: number) => `/profile/${profileId}?modal=create`,
  FAVORITES: '/favorites',
  FORGOT_PASSWORD: '/auth/forgot-password',
  HOME: '/',
  LOGIN: '/auth/login',
  MESSENGER: '/messenger',
  POST: (profileId: number, id: number) => `/profile/${profileId}/?post=${id}`,
  PRIVACY_POLICY: '/policies/privacy-policy',
  PROFILE: (profileId: number) => `/profile/${profileId}`,
  PROFILE_SETTINGS: (profileId: number) => `/profile/${profileId}/settings`,
  REGISTRATION: '/auth/registration',
  SEARCH: '/search',
  STATISTICS: '/statistics',
  TERMS_OF_SERVICE: '/policies/terms-of-service',
}
