export enum TypographyVariant {
  BoldText14 = 'bold-text-14',
  BoldText16 = 'bold-text-16',
  H1 = 'h1',
  H2 = 'h2',
  H3 = 'h3',
  Large = 'large',
  MediumText14 = 'medium-text-14',
  RegularLink = 'regular-link',
  RegularText14 = 'regular-text-14',
  RegularText16 = 'regular-text-16',
  SemiBoldSmallText = 'semi-bold-small-text',
  SmallLink = 'small-link',
  SmallText = 'small-text',
}
